a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))

print("a + b=", a + b)
print("a - b=", a - b)
print("a * b=", a * b)
print("a ^ b=", a ** b)
print("a % b=", a % b)
print("a // b=", a // b)

x1 = (((17 / 2) * 3) + 2)
x2 = (2 + ((17 / 2) * 3))
x3 = ((19 % 4) + ((15 / 2) * 3))
x4 = ((15 + 6) - (10 * 4))
x5 = (((17 / 2) % 2) * (3 ** 3))
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)

x = int(input("Введите x: "))
y = int(input("Введите y: "))
print((abs(x) - abs(y)) / (1 + abs(x * y)))
